import type {
  PrototypeLexeme,
  PrototypeSense,
  PrototypeStory,
  PrototypeStoryOccurrence,
} from "@/lib/lexical-prototype";

const STORY_ID = "a1-m1-i1-s1";

const lexemes: readonly PrototypeLexeme[] = [
  { id: "lex-ir", canonicalForm: "ir", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-mercado", canonicalForm: "mercado", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-querer", canonicalForm: "querer", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-comprar", canonicalForm: "comprar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-fruta", canonicalForm: "fruta", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-preparar", canonicalForm: "preparar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-cena", canonicalForm: "cena", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-tienda", canonicalForm: "tienda", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-ver", canonicalForm: "ver", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-manzana", canonicalForm: "manzana", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-rojo", canonicalForm: "rojo", partOfSpeech: "ADJ", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-naranja", canonicalForm: "naranja", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-pan", canonicalForm: "pan", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-buscar", canonicalForm: "buscar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-leche", canonicalForm: "leche", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-llegar", canonicalForm: "llegar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-casa", canonicalForm: "casa", partOfSpeech: "NOUN", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-darse-cuenta", canonicalForm: "darse cuenta", partOfSpeech: "VERB", lexicalType: "MULTIWORD", pronominality: "OBLIGATORY" },
  { id: "lex-olvidar", canonicalForm: "olvidar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-volver", canonicalForm: "volver", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-cenar", canonicalForm: "cenar", partOfSpeech: "VERB", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
  { id: "lex-juntos", canonicalForm: "juntos", partOfSpeech: "ADV", lexicalType: "SINGLE_WORD", pronominality: "NONE" },
];

const senses: readonly PrototypeSense[] = [
  { id: "sense-ir-move", lexemeId: "lex-ir", glossEn: "to go", definitionEs: "desplazarse hacia otro lugar" },
  { id: "sense-mercado-place", lexemeId: "lex-mercado", glossEn: "market", definitionEs: "lugar donde se compran y venden productos" },
  { id: "sense-querer-want", lexemeId: "lex-querer", glossEn: "to want", definitionEs: "tener deseo o intención de hacer algo" },
  { id: "sense-comprar-buy", lexemeId: "lex-comprar", glossEn: "to buy", definitionEs: "obtener algo a cambio de dinero" },
  { id: "sense-fruta-food", lexemeId: "lex-fruta", glossEn: "fruit", definitionEs: "alimento vegetal producido por ciertas plantas" },
  { id: "sense-preparar-make", lexemeId: "lex-preparar", glossEn: "to prepare", definitionEs: "hacer lo necesario para que algo quede listo" },
  { id: "sense-cena-meal", lexemeId: "lex-cena", glossEn: "dinner", definitionEs: "comida que se toma normalmente por la noche" },
  { id: "sense-tienda-shop", lexemeId: "lex-tienda", glossEn: "shop / store", definitionEs: "establecimiento donde se venden productos" },
  { id: "sense-ver-see", lexemeId: "lex-ver", glossEn: "to see", definitionEs: "percibir algo con la vista" },
  { id: "sense-manzana-fruit", lexemeId: "lex-manzana", glossEn: "apple", definitionEs: "fruta redonda que crece en el manzano" },
  { id: "sense-rojo-color", lexemeId: "lex-rojo", glossEn: "red", definitionEs: "de color rojo" },
  { id: "sense-naranja-fruit", lexemeId: "lex-naranja", glossEn: "orange", definitionEs: "fruta cítrica de color anaranjado" },
  { id: "sense-pan-food", lexemeId: "lex-pan", glossEn: "bread", definitionEs: "alimento hecho principalmente con harina y agua" },
  { id: "sense-buscar-look", lexemeId: "lex-buscar", glossEn: "to look for", definitionEs: "intentar encontrar a alguien o algo" },
  { id: "sense-leche-food", lexemeId: "lex-leche", glossEn: "milk", definitionEs: "líquido alimenticio de origen animal o vegetal" },
  { id: "sense-llegar-arrive", lexemeId: "lex-llegar", glossEn: "to arrive", definitionEs: "alcanzar el lugar al que se iba" },
  { id: "sense-casa-home", lexemeId: "lex-casa", glossEn: "house / home", definitionEs: "lugar destinado a vivir" },
  { id: "sense-darse-cuenta-realize", lexemeId: "lex-darse-cuenta", glossEn: "to realize", definitionEs: "comprender o advertir algo que antes no se había notado" },
  { id: "sense-olvidar-forget", lexemeId: "lex-olvidar", glossEn: "to forget", definitionEs: "dejar de recordar algo o no tenerlo presente" },
  { id: "sense-volver-return", lexemeId: "lex-volver", glossEn: "to return", definitionEs: "ir de nuevo al lugar del que se salió" },
  { id: "sense-cenar-dine", lexemeId: "lex-cenar", glossEn: "to have dinner", definitionEs: "tomar la comida de la noche" },
  { id: "sense-juntos-together", lexemeId: "lex-juntos", glossEn: "together", definitionEs: "en compañía o en unión con otra persona" },
];

function singleOccurrence(
  id: string,
  sentenceId: string,
  lexemeId: string,
  senseId: string,
  surface: string,
): PrototypeStoryOccurrence {
  return {
    id,
    storyId: STORY_ID,
    sentenceId,
    lexemeId,
    senseId,
    surface,
    parts: [{ id: `${id}-head`, text: surface, role: "HEAD" }],
  };
}

const occurrences: readonly PrototypeStoryOccurrence[] = [
  singleOccurrence("occ-fue", "s1", "lex-ir", "sense-ir-move", "fue"),
  singleOccurrence("occ-mercado-1", "s1", "lex-mercado", "sense-mercado-place", "mercado"),
  singleOccurrence("occ-queria", "s2", "lex-querer", "sense-querer-want", "Quería"),
  singleOccurrence("occ-comprar", "s2", "lex-comprar", "sense-comprar-buy", "comprar"),
  singleOccurrence("occ-fruta", "s2", "lex-fruta", "sense-fruta-food", "fruta"),
  singleOccurrence("occ-preparar", "s2", "lex-preparar", "sense-preparar-make", "preparar"),
  singleOccurrence("occ-cena", "s2", "lex-cena", "sense-cena-meal", "cena"),
  singleOccurrence("occ-tienda", "s3", "lex-tienda", "sense-tienda-shop", "tienda"),
  singleOccurrence("occ-vio", "s3", "lex-ver", "sense-ver-see", "vio"),
  singleOccurrence("occ-manzanas", "s3", "lex-manzana", "sense-manzana-fruit", "manzanas"),
  singleOccurrence("occ-rojas", "s3", "lex-rojo", "sense-rojo-color", "rojas"),
  singleOccurrence("occ-naranjas", "s3", "lex-naranja", "sense-naranja-fruit", "naranjas"),
  singleOccurrence("occ-compro-1", "s4", "lex-comprar", "sense-comprar-buy", "compró"),
  singleOccurrence("occ-pan", "s4", "lex-pan", "sense-pan-food", "pan"),
  singleOccurrence("occ-buscaba", "s4", "lex-buscar", "sense-buscar-look", "buscaba"),
  singleOccurrence("occ-leche-1", "s4", "lex-leche", "sense-leche-food", "leche"),
  singleOccurrence("occ-llegaron", "s5", "lex-llegar", "sense-llegar-arrive", "llegaron"),
  singleOccurrence("occ-casa", "s5", "lex-casa", "sense-casa-home", "casa"),
  {
    id: "occ-se-dio-cuenta",
    storyId: STORY_ID,
    sentenceId: "s5",
    lexemeId: "lex-darse-cuenta",
    senseId: "sense-darse-cuenta-realize",
    surface: "se dio cuenta",
    parts: [
      { id: "occ-se-dio-cuenta-clitic", text: "se", role: "CLITIC" },
      { id: "occ-se-dio-cuenta-head", text: "dio", role: "HEAD" },
      { id: "occ-se-dio-cuenta-fixed", text: "cuenta", role: "FIXED" },
    ],
  },
  singleOccurrence("occ-olvidado", "s5", "lex-olvidar", "sense-olvidar-forget", "olvidado"),
  singleOccurrence("occ-leche-2", "s5", "lex-leche", "sense-leche-food", "leche"),
  singleOccurrence("occ-volvio", "s6", "lex-volver", "sense-volver-return", "volvió"),
  singleOccurrence("occ-mercado-2", "s6", "lex-mercado", "sense-mercado-place", "mercado"),
  singleOccurrence("occ-compro-2", "s6", "lex-comprar", "sense-comprar-buy", "compró"),
  singleOccurrence("occ-cenaron", "s7", "lex-cenar", "sense-cenar-dine", "cenaron"),
  singleOccurrence("occ-juntos", "s7", "lex-juntos", "sense-juntos-together", "juntos"),
];

export const A1_STORY_1: PrototypeStory = {
  id: STORY_ID,
  title: "La compra olvidada",
  summary: "Marta y Carlos hacen una compra sencilla, pero al llegar a casa descubren que falta algo importante.",
  lexemes,
  senses,
  occurrences,
  sentences: [
    {
      id: "s1",
      segments: [
        { text: "Ayer Marta " },
        { text: "fue", occurrenceId: "occ-fue" },
        { text: " al " },
        { text: "mercado", occurrenceId: "occ-mercado-1" },
        { text: " con Carlos." },
      ],
    },
    {
      id: "s2",
      segments: [
        { text: "Quería", occurrenceId: "occ-queria" },
        { text: " " },
        { text: "comprar", occurrenceId: "occ-comprar" },
        { text: " " },
        { text: "fruta", occurrenceId: "occ-fruta" },
        { text: " para " },
        { text: "preparar", occurrenceId: "occ-preparar" },
        { text: " la " },
        { text: "cena", occurrenceId: "occ-cena" },
        { text: "." },
      ],
    },
    {
      id: "s3",
      segments: [
        { text: "En una " },
        { text: "tienda", occurrenceId: "occ-tienda" },
        { text: " " },
        { text: "vio", occurrenceId: "occ-vio" },
        { text: " " },
        { text: "manzanas", occurrenceId: "occ-manzanas" },
        { text: " " },
        { text: "rojas", occurrenceId: "occ-rojas" },
        { text: " y " },
        { text: "naranjas", occurrenceId: "occ-naranjas" },
        { text: "." },
      ],
    },
    {
      id: "s4",
      segments: [
        { text: "Carlos " },
        { text: "compró", occurrenceId: "occ-compro-1" },
        { text: " " },
        { text: "pan", occurrenceId: "occ-pan" },
        { text: " mientras Marta " },
        { text: "buscaba", occurrenceId: "occ-buscaba" },
        { text: " " },
        { text: "leche", occurrenceId: "occ-leche-1" },
        { text: "." },
      ],
    },
    {
      id: "s5",
      segments: [
        { text: "Cuando " },
        { text: "llegaron", occurrenceId: "occ-llegaron" },
        { text: " a " },
        { text: "casa", occurrenceId: "occ-casa" },
        { text: ", Marta " },
        { text: "se dio cuenta", occurrenceId: "occ-se-dio-cuenta" },
        { text: " de que había " },
        { text: "olvidado", occurrenceId: "occ-olvidado" },
        { text: " la " },
        { text: "leche", occurrenceId: "occ-leche-2" },
        { text: "." },
      ],
    },
    {
      id: "s6",
      segments: [
        { text: "Carlos " },
        { text: "volvió", occurrenceId: "occ-volvio" },
        { text: " al " },
        { text: "mercado", occurrenceId: "occ-mercado-2" },
        { text: " y la " },
        { text: "compró", occurrenceId: "occ-compro-2" },
        { text: "." },
      ],
    },
    {
      id: "s7",
      segments: [
        { text: "Después " },
        { text: "cenaron", occurrenceId: "occ-cenaron" },
        { text: " " },
        { text: "juntos", occurrenceId: "occ-juntos" },
        { text: "." },
      ],
    },
  ],
};
